// Code generated by counterfeiter. DO NOT EDIT.
package apifakes

import (
	"context"
	"sync"

	"github.com/dembygenesis/local.tools/internal/model"
)

type FakeClickTrackerService struct {
	AddClickTrackerStub        func(context.Context, *model.CreateClickTracker) (*model.ClickTracker, error)
	addClickTrackerMutex       sync.RWMutex
	addClickTrackerArgsForCall []struct {
		arg1 context.Context
		arg2 *model.CreateClickTracker
	}
	addClickTrackerReturns struct {
		result1 *model.ClickTracker
		result2 error
	}
	addClickTrackerReturnsOnCall map[int]struct {
		result1 *model.ClickTracker
		result2 error
	}
	ListClickTrackersStub        func(context.Context, *model.ClickTrackerFilters) (*model.PaginatedClickTrackers, error)
	listClickTrackersMutex       sync.RWMutex
	listClickTrackersArgsForCall []struct {
		arg1 context.Context
		arg2 *model.ClickTrackerFilters
	}
	listClickTrackersReturns struct {
		result1 *model.PaginatedClickTrackers
		result2 error
	}
	listClickTrackersReturnsOnCall map[int]struct {
		result1 *model.PaginatedClickTrackers
		result2 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeClickTrackerService) AddClickTracker(arg1 context.Context, arg2 *model.CreateClickTracker) (*model.ClickTracker, error) {
	fake.addClickTrackerMutex.Lock()
	ret, specificReturn := fake.addClickTrackerReturnsOnCall[len(fake.addClickTrackerArgsForCall)]
	fake.addClickTrackerArgsForCall = append(fake.addClickTrackerArgsForCall, struct {
		arg1 context.Context
		arg2 *model.CreateClickTracker
	}{arg1, arg2})
	stub := fake.AddClickTrackerStub
	fakeReturns := fake.addClickTrackerReturns
	fake.recordInvocation("AddClickTracker", []interface{}{arg1, arg2})
	fake.addClickTrackerMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeClickTrackerService) AddClickTrackerCallCount() int {
	fake.addClickTrackerMutex.RLock()
	defer fake.addClickTrackerMutex.RUnlock()
	return len(fake.addClickTrackerArgsForCall)
}

func (fake *FakeClickTrackerService) AddClickTrackerCalls(stub func(context.Context, *model.CreateClickTracker) (*model.ClickTracker, error)) {
	fake.addClickTrackerMutex.Lock()
	defer fake.addClickTrackerMutex.Unlock()
	fake.AddClickTrackerStub = stub
}

func (fake *FakeClickTrackerService) AddClickTrackerArgsForCall(i int) (context.Context, *model.CreateClickTracker) {
	fake.addClickTrackerMutex.RLock()
	defer fake.addClickTrackerMutex.RUnlock()
	argsForCall := fake.addClickTrackerArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *FakeClickTrackerService) AddClickTrackerReturns(result1 *model.ClickTracker, result2 error) {
	fake.addClickTrackerMutex.Lock()
	defer fake.addClickTrackerMutex.Unlock()
	fake.AddClickTrackerStub = nil
	fake.addClickTrackerReturns = struct {
		result1 *model.ClickTracker
		result2 error
	}{result1, result2}
}

func (fake *FakeClickTrackerService) AddClickTrackerReturnsOnCall(i int, result1 *model.ClickTracker, result2 error) {
	fake.addClickTrackerMutex.Lock()
	defer fake.addClickTrackerMutex.Unlock()
	fake.AddClickTrackerStub = nil
	if fake.addClickTrackerReturnsOnCall == nil {
		fake.addClickTrackerReturnsOnCall = make(map[int]struct {
			result1 *model.ClickTracker
			result2 error
		})
	}
	fake.addClickTrackerReturnsOnCall[i] = struct {
		result1 *model.ClickTracker
		result2 error
	}{result1, result2}
}

func (fake *FakeClickTrackerService) ListClickTrackers(arg1 context.Context, arg2 *model.ClickTrackerFilters) (*model.PaginatedClickTrackers, error) {
	fake.listClickTrackersMutex.Lock()
	ret, specificReturn := fake.listClickTrackersReturnsOnCall[len(fake.listClickTrackersArgsForCall)]
	fake.listClickTrackersArgsForCall = append(fake.listClickTrackersArgsForCall, struct {
		arg1 context.Context
		arg2 *model.ClickTrackerFilters
	}{arg1, arg2})
	stub := fake.ListClickTrackersStub
	fakeReturns := fake.listClickTrackersReturns
	fake.recordInvocation("ListClickTrackers", []interface{}{arg1, arg2})
	fake.listClickTrackersMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeClickTrackerService) ListClickTrackersCallCount() int {
	fake.listClickTrackersMutex.RLock()
	defer fake.listClickTrackersMutex.RUnlock()
	return len(fake.listClickTrackersArgsForCall)
}

func (fake *FakeClickTrackerService) ListClickTrackersCalls(stub func(context.Context, *model.ClickTrackerFilters) (*model.PaginatedClickTrackers, error)) {
	fake.listClickTrackersMutex.Lock()
	defer fake.listClickTrackersMutex.Unlock()
	fake.ListClickTrackersStub = stub
}

func (fake *FakeClickTrackerService) ListClickTrackersArgsForCall(i int) (context.Context, *model.ClickTrackerFilters) {
	fake.listClickTrackersMutex.RLock()
	defer fake.listClickTrackersMutex.RUnlock()
	argsForCall := fake.listClickTrackersArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *FakeClickTrackerService) ListClickTrackersReturns(result1 *model.PaginatedClickTrackers, result2 error) {
	fake.listClickTrackersMutex.Lock()
	defer fake.listClickTrackersMutex.Unlock()
	fake.ListClickTrackersStub = nil
	fake.listClickTrackersReturns = struct {
		result1 *model.PaginatedClickTrackers
		result2 error
	}{result1, result2}
}

func (fake *FakeClickTrackerService) ListClickTrackersReturnsOnCall(i int, result1 *model.PaginatedClickTrackers, result2 error) {
	fake.listClickTrackersMutex.Lock()
	defer fake.listClickTrackersMutex.Unlock()
	fake.ListClickTrackersStub = nil
	if fake.listClickTrackersReturnsOnCall == nil {
		fake.listClickTrackersReturnsOnCall = make(map[int]struct {
			result1 *model.PaginatedClickTrackers
			result2 error
		})
	}
	fake.listClickTrackersReturnsOnCall[i] = struct {
		result1 *model.PaginatedClickTrackers
		result2 error
	}{result1, result2}
}

func (fake *FakeClickTrackerService) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	fake.addClickTrackerMutex.RLock()
	defer fake.addClickTrackerMutex.RUnlock()
	fake.listClickTrackersMutex.RLock()
	defer fake.listClickTrackersMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeClickTrackerService) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}
